In [7]:
import pandas as pd
from transformers import AutoTokenizer

In [12]:
df = pd.read_excel("training_set_rel3.xlsx")
# df = df[df['essay_set'] == 1]
df = df[['essay_set', 'essay']]
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12978 entries, 0 to 12977
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   essay_set  12978 non-null  int64
 1   essay      12978 non-null  object
dtypes: int64(1), object(1)
memory usage: 202.9+ KB
None

   essay_set                                              essay
0          1  Dear local newspaper, I think effects computer...
1          1  Dear @CAPS1 @CAPS2, I believe that using compu...
2          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...
3          1  Dear Local Newspaper, @CAPS1 I have found that...
4          1  Dear @LOCATION1, I know having computers has a...

In [13]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [14]:
def get_length(text):
    encoding = tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            return_tensors='pt',
        )
    return encoding['input_ids'].flatten().shape[0]

df['essay_len'] = df['essay'].apply(get_length)

Token indices sequence length is longer than the specified maximum sequence length for this model (723 > 512). Running this sequence through the model will result in indexing errors

In [19]:
print("essay 1")
print(df[df['essay_set'] == 1]['essay_len'].describe())

print("essay 2")
print(df[df['essay_set'] == 2]['essay_len'].describe())

print("essay 3")
print(df[df['essay_set'] == 3]['essay_len'].describe())

print("essay 4")
print(df[df['essay_set'] == 4]['essay_len'].describe())

print("essay 5")
print(df[df['essay_set'] == 5]['essay_len'].describe())

print("essay 6")
print(df[df['essay_set'] == 6]['essay_len'].describe())

print("essay 7")
print(df[df['essay_set'] == 7]['essay_len'].describe())

print("essay 8")
print(df[df['essay_set'] == 8]['essay_len'].describe())

essay 1
count    1783.000000
mean      452.664049
std       152.964730
min        12.000000
25%       351.000000
50%       449.000000
75%       547.000000
max      1023.000000
Name: essay_len, dtype: float64
essay 2
count    1800.000000
mean      459.068333
std       187.569105
min        37.000000
25%       335.000000
50%       443.000000
75%       567.000000
max      1237.000000
Name: essay_len, dtype: float64
essay 3
count    1726.000000
mean      133.313441
std        66.060874
min        12.000000
25%        81.250000
50%       122.000000
75%       179.000000
max       473.000000
Name: essay_len, dtype: float64
essay 4
count    1772.000000
mean      115.459368
std        64.693946
min         4.000000
25%        64.000000
50%       106.000000
75%       156.000000
max       450.000000
Name: essay_len, dtype: float64
essay 5
count    1805.000000
mean      154.251524
std        73.926807
min         7.000000
25%        98.000000
50%       148.000000
75%       199.000000
max       526.000000
Name: essay_len, dtype: float64
essay 6
count    1800.000000
mean      195.231111
std        71.808636
min         6.000000
25%       148.750000
50%       196.000000
75%       239.000000
max       561.000000
Name: essay_len, dtype: float64
essay 7
count    1569.000000
mean      217.837476
std       117.971777
min         8.000000
25%       134.000000
50%       196.000000
75%       275.000000
max       851.000000
Name: essay_len, dtype: float64
essay 8
count     723.000000
mean      752.237898
std       265.121336
min         7.000000
25%       563.500000
50%       775.000000
75%       971.500000
max      1413.000000
Name: essay_len, dtype: float64

In [20]:
new_df = df[df['essay_set'] == 8]
print(new_df.info())
new_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 723 entries, 12255 to 12977
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   essay_set  723 non-null    int64
 1   essay      723 non-null    object
 2   essay_len  723 non-null    int64
dtypes: int64(2), object(1)
memory usage: 22.6+ KB
None

       essay_set                                              essay  essay_len
12255          8   A long time ago when I was in third grade I h...        918
12256          8   Softball has to be one of the single most gre...        893
12257          8   Some people like making people laugh, I love ...       1012
12258          8   "LAUGHTER"  @CAPS1 I hang out with my friends...        798
12259          8  Well ima tell a story about the time i got @CA...        791