In [2]:
import pandas as pd
import numpy as np
import regex as re

## Rahumoto Dataset

In [43]:
df = pd.read_csv('../data/aes_dataset_5k_clean.csv')
df = df[df['dataset'] == 'analisis_essay'][['question', 'reference_answer', 'answer', 'score', 'normalized_score', 'dataset', 'dataset_num']]
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2162 entries, 0 to 2161
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          2162 non-null   object
 1   reference_answer  2162 non-null   object
 2   answer            2162 non-null   object
 3   score             2162 non-null   float64
 4   normalized_score  2162 non-null   float64
 5   dataset           2162 non-null   object
 6   dataset_num       2162 non-null   object
dtypes: float64(2), object(5)
memory usage: 135.1+ KB
None

,question,reference_answer,answer,score,normalized_score,dataset,dataset_num
0,Jelaskan kegunaan karbohidrat untuk tubuh kita.,Fungsi karbohidrat adalah sebagai pemasok ener...,"sumber tenaga, pemanis alami, menjaga sistem i...",27.0,0.27,analisis_essay,analisis_essay-1
1,Jelaskan kegunaan karbohidrat untuk tubuh kita.,Fungsi karbohidrat adalah sebagai pemasok ener...,"sebagai sumber energi, pemanis alami, menjaga ...",21.0,0.21,analisis_essay,analisis_essay-1
2,Jelaskan kegunaan karbohidrat untuk tubuh kita.,Fungsi karbohidrat adalah sebagai pemasok ener...,1. Sebagai energi. 2. Sebagai memperlancaar pe...,42.0,0.42,analisis_essay,analisis_essay-1
3,Jelaskan kegunaan karbohidrat untuk tubuh kita.,Fungsi karbohidrat adalah sebagai pemasok ener...,"untuk membuat kenyang, agar tidak lapar, agar ...",18.0,0.18,analisis_essay,analisis_essay-1
4,Jelaskan kegunaan karbohidrat untuk tubuh kita.,Fungsi karbohidrat adalah sebagai pemasok ener...,Karbohidrat mempunyai peran penting untuk pros...,82.0,0.82,analisis_essay,analisis_essay-1

In [45]:
remove_question = ["analisis_essay-1", "analisis_essay-11", "analisis_essay-21", "analisis_essay-31"]
df_seen = df[~df['dataset_num'].isin(remove_question)].reset_index(drop=True)
print(df_seen.info())
df_seen.head()
df_seen.to_csv("aes_dataset_indo.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1943 entries, 0 to 1942
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          1943 non-null   object
 1   reference_answer  1943 non-null   object
 2   answer            1943 non-null   object
 3   score             1943 non-null   float64
 4   normalized_score  1943 non-null   float64
 5   dataset           1943 non-null   object
 6   dataset_num       1943 non-null   object
dtypes: float64(2), object(5)
memory usage: 106.4+ KB
None

In [46]:
df_unseen = df[df['dataset_num'].isin(remove_question)].reset_index(drop=True)
print(df_unseen.info())
df_unseen.head()
df_unseen.to_csv("aes_dataset_indo_unseen.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          219 non-null    object
 1   reference_answer  219 non-null    object
 2   answer            219 non-null    object
 3   score             219 non-null    float64
 4   normalized_score  219 non-null    float64
 5   dataset           219 non-null    object
 6   dataset_num       219 non-null    object
dtypes: float64(2), object(5)
memory usage: 12.1+ KB
None

## SAG Dataset

In [29]:
df_sag = pd.read_csv('../data/aes_dataset_5k_clean.csv')
df_sag = df_sag[df_sag['dataset'] == 'sag'][['question', 'reference_answer', 'answer', 'score', 'normalized_score', 'dataset']].reset_index(drop=True)
df_sag["dataset_num"] = df_sag.groupby("dataset")["question"].transform(
    lambda x: ["sag-" + str(i + 1) for i in pd.factorize(x)[0]]
)
print(df_sag.info())
df_sag.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2326 entries, 0 to 2325
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          2326 non-null   object
 1   reference_answer  2326 non-null   object
 2   answer            2326 non-null   object
 3   score             2326 non-null   float64
 4   normalized_score  2326 non-null   float64
 5   dataset           2326 non-null   object
 6   dataset_num       2326 non-null   object
dtypes: float64(2), object(5)
memory usage: 127.3+ KB
None

,question,reference_answer,answer,score,normalized_score,dataset,dataset_num
0,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,High risk problems are address in the prototyp...,3.5,0.7,sag,sag-1
1,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,To simulate portions of the desired final prod...,5.0,1.0,sag,sag-1
2,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,A prototype program simulates the behaviors of...,4.0,0.8,sag,sag-1
3,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,Defined in the Specification phase a prototype...,5.0,1.0,sag,sag-1
4,What is the role of a prototype program in pro...,To simulate the behaviour of portions of the d...,It is used to let the users have a first idea ...,3.0,0.6,sag,sag-1

In [35]:
remove_question = ["sag-75", "sag-76", "sag-77","sag-78", "sag-79", "sag-80", "sag-81", "sag-82"]
df_sag_seen = df_sag[~df_sag['dataset_num'].isin(remove_question)].reset_index(drop=True)
print(df_sag_seen.info())
df_sag_seen.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          2100 non-null   object
 1   reference_answer  2100 non-null   object
 2   answer            2100 non-null   object
 3   score             2100 non-null   float64
 4   normalized_score  2100 non-null   float64
 5   dataset           2100 non-null   object
 6   dataset_num       2100 non-null   object
dtypes: float64(2), object(5)
memory usage: 115.0+ KB
None

,question,reference_answer,answer,score,normalized_score,dataset,dataset_num
2095,What is a queue?,A data structure that stores elements followin...,a queue is a set of elements where the first e...,5.0,1.0,sag,sag-54
2096,What is a queue?,A data structure that stores elements followin...,Is a list of items where the the user only has...,5.0,1.0,sag,sag-54
2097,What is a queue?,A data structure that stores elements followin...,a queue is a list of data that follows the fif...,5.0,1.0,sag,sag-54
2098,What is a queue?,A data structure that stores elements followin...,A queue is a data structure that holds a set o...,5.0,1.0,sag,sag-54
2099,What is a queue?,A data structure that stores elements followin...,like a linked list expect first in last out,1.5,0.3,sag,sag-54

In [36]:
df_sag_unseen = df_sag[df_sag['dataset_num'].isin(remove_question)].reset_index(drop=True)
print(df_sag_unseen.info())
df_sag_unseen.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          226 non-null    object
 1   reference_answer  226 non-null    object
 2   answer            226 non-null    object
 3   score             226 non-null    float64
 4   normalized_score  226 non-null    float64
 5   dataset           226 non-null    object
 6   dataset_num       226 non-null    object
dtypes: float64(2), object(5)
memory usage: 12.5+ KB
None

,question,reference_answer,answer,score,normalized_score,dataset,dataset_num
0,Briefly describe the divide-and-conquer paradigm.,"Divide a problem into smaller subproblems, sol...","For example we have an array on n elements, th...",4.0,0.8,sag,sag-75
1,Briefly describe the divide-and-conquer paradigm.,"Divide a problem into smaller subproblems, sol...",Divide and coquer means dividing a problem int...,5.0,1.0,sag,sag-75
2,Briefly describe the divide-and-conquer paradigm.,"Divide a problem into smaller subproblems, sol...",The divide and conquer paradigm divides a prob...,4.5,0.9,sag,sag-75
3,Briefly describe the divide-and-conquer paradigm.,"Divide a problem into smaller subproblems, sol...","Divide elements, recur then conquer, which wor...",4.0,0.8,sag,sag-75
4,Briefly describe the divide-and-conquer paradigm.,"Divide a problem into smaller subproblems, sol...","To divide and conquer, you divide the program ...",4.5,0.9,sag,sag-75

## Concat dataset

In [41]:
new_df = pd.concat([df_seen, df_sag_seen], axis=0)
print(new_df.info())
new_df.head()
new_df.to_csv("clean_df.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 4043 entries, 0 to 2099
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          4043 non-null   object
 1   reference_answer  4043 non-null   object
 2   answer            4043 non-null   object
 3   score             4043 non-null   float64
 4   normalized_score  4043 non-null   float64
 5   dataset           4043 non-null   object
 6   dataset_num       4043 non-null   object
dtypes: float64(2), object(5)
memory usage: 252.7+ KB
None

In [42]:
new_df_unseen = pd.concat([df_unseen, df_sag_unseen], axis=0)
print(new_df_unseen.info())
new_df_unseen.tail()
new_df_unseen.to_csv("clean_df_unseen.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 445 entries, 0 to 225
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          445 non-null    object
 1   reference_answer  445 non-null    object
 2   answer            445 non-null    object
 3   score             445 non-null    float64
 4   normalized_score  445 non-null    float64
 5   dataset           445 non-null    object
 6   dataset_num       445 non-null    object
dtypes: float64(2), object(5)
memory usage: 27.8+ KB
None

In [14]:
df = pd.read_csv("../data/aes_dataset_new.csv")
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4043 entries, 0 to 4042
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          4043 non-null   object
 1   reference_answer  4043 non-null   object
 2   answer            4043 non-null   object
 3   score             4043 non-null   float64
 4   normalized_score  4043 non-null   float64
 5   dataset           4043 non-null   object
 6   dataset_num       4043 non-null   object
dtypes: float64(2), object(5)
memory usage: 221.2+ KB
None

,question,reference_answer,answer,score,normalized_score,dataset,dataset_num
0,Deskripsikan 4 manfaat telur untuk kesehatan?,1. Bermanfaat untuk pasien kemoterapi Karena k...,- memberi tenaga - menjaga metabolisme - membu...,12.0,0.12,analisis_essay,analisis_essay-2
1,Deskripsikan 4 manfaat telur untuk kesehatan?,1. Bermanfaat untuk pasien kemoterapi Karena k...,sebagai sumber protein sebagai sumber lemak se...,13.0,0.13,analisis_essay,analisis_essay-2
2,Deskripsikan 4 manfaat telur untuk kesehatan?,1. Bermanfaat untuk pasien kemoterapi Karena k...,1. Sumber makanan. 2. Sumber energi. 3. Sumber...,18.0,0.18,analisis_essay,analisis_essay-2
3,Deskripsikan 4 manfaat telur untuk kesehatan?,1. Bermanfaat untuk pasien kemoterapi Karena k...,"sumber protein yang digunakan oleh tubuh, untu...",11.0,0.11,analisis_essay,analisis_essay-2
4,Deskripsikan 4 manfaat telur untuk kesehatan?,1. Bermanfaat untuk pasien kemoterapi Karena k...,Telur mengandung banyak protein yang berfungsi...,47.0,0.47,analisis_essay,analisis_essay-2

In [15]:
df_swapped = df.rename(columns={"reference_answer": "answer", "answer": "reference_answer"})
df_siamese = pd.concat([df, df_swapped], ignore_index=True)
print(df_siamese.info())
df_siamese.tail()
df_siamese.to_csv("aes_dataset_new_siamese.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8086 entries, 0 to 8085
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   question          8086 non-null   object
 1   reference_answer  8086 non-null   object
 2   answer            8086 non-null   object
 3   score             8086 non-null   float64
 4   normalized_score  8086 non-null   float64
 5   dataset           8086 non-null   object
 6   dataset_num       8086 non-null   object
dtypes: float64(2), object(5)
memory usage: 442.3+ KB
None